/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxlamFuZHJvZy9lLVR1dG9yaWFscy9Bbmd1bGFyL2RlcGxveS1kZW1vLW1vc2gvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvYWxlamFuZHJvZy9lLVR1dG9yaWFscy9Bbmd1bGFyL2RlcGxveS1kZW1vLW1vc2gvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
