/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxlamFuZHJvZy9lLVR1dG9yaWFscy9Bbmd1bGFyL2RlcGxveS1kZW1vLW1vc2gvc3JjL2FwcC9naXRodWItZm9sbG93ZXJzL2dpdGh1Yi1mb2xsb3dlcnMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FsZWphbmRyb2cvZS1UdXRvcmlhbHMvQW5ndWxhci9kZXBsb3ktZGVtby1tb3NoL3NyYy9hcHAvZ2l0aHViLWZvbGxvd2Vycy9naXRodWItZm9sbG93ZXJzLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
